-- TBL_CALENDAR_DATE: 달력 (일자)
CREATE TABLE TBL_CALENDAR_DATE (
    CALENDAR_DATE DATE PRIMARY KEY,
    DAY_OF_WEEK VARCHAR2(3 CHAR)
);

COMMENT ON TABLE TBL_CALENDAR_DATE IS '달력 (일자)';
COMMENT ON COLUMN TBL_CALENDAR_DATE.CALENDAR_DATE IS '날짜 (PK)';
COMMENT ON COLUMN TBL_CALENDAR_DATE.DAY_OF_WEEK IS '요일 (예: 월, 화 등)';


-- TBL_ROUTINE_CHECK: 루틴 체크 (메인)
CREATE TABLE TBL_ROUTINE_CHECK (
    ID NUMBER PRIMARY KEY,
    CHECK_TIME TIMESTAMP,
    TEMPLATE_ID VARCHAR2(10 CHAR) NOT NULL,
    TEMPLATE_TYPE VARCHAR2(20 CHAR),
    STATUS VARCHAR2(20 CHAR),
    REMARK VARCHAR2(400 CHAR),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR2(36 CHAR),
    UPDATED_AT TIMESTAMP,
    UPDATED_BY VARCHAR2(36 CHAR)
);

COMMENT ON TABLE TBL_ROUTINE_CHECK IS '루틴 체크 (메인)';
COMMENT ON COLUMN TBL_ROUTINE_CHECK.ID IS '체크 ID (PK)';
COMMENT ON COLUMN TBL_ROUTINE_CHECK.CHECK_TIME IS '체크한 시각';
COMMENT ON COLUMN TBL_ROUTINE_CHECK.TEMPLATE_ID IS '템플릿 ID 참조';
COMMENT ON COLUMN TBL_ROUTINE_CHECK.TEMPLATE_TYPE IS '템플릿 종류';
COMMENT ON COLUMN TBL_ROUTINE_CHECK.STATUS IS '루틴 전체 상태';
COMMENT ON COLUMN TBL_ROUTINE_CHECK.REMARK IS '비고';
COMMENT ON COLUMN TBL_ROUTINE_CHECK.CREATED_AT IS '생성 시각';
COMMENT ON COLUMN TBL_ROUTINE_CHECK.CREATED_BY IS '생성자';
COMMENT ON COLUMN TBL_ROUTINE_CHECK.UPDATED_AT IS '수정 시각';
COMMENT ON COLUMN TBL_ROUTINE_CHECK.UPDATED_BY IS '수정자';


-- TBL_ROUTINE_CHECK_ITEM: 루틴 체크 상세 항목
CREATE TABLE TBL_ROUTINE_CHECK_ITEM (
    ID NUMBER PRIMARY KEY,
    CHECK_ID NUMBER NOT NULL,
    ITEM_ID VARCHAR2(20 CHAR) NOT NULL,
    IS_CHECKED CHAR(1),
    CHECK_TIME TIMESTAMP,
    REMARK VARCHAR2(400 CHAR),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR2(36 CHAR),
    UPDATED_AT TIMESTAMP,
    UPDATED_BY VARCHAR2(36 CHAR)
);

COMMENT ON TABLE TBL_ROUTINE_CHECK_ITEM IS '루틴 체크 (상세항목)';
COMMENT ON COLUMN TBL_ROUTINE_CHECK_ITEM.ID IS '체크 항목 ID (PK)';
COMMENT ON COLUMN TBL_ROUTINE_CHECK_ITEM.CHECK_ID IS '루틴 체크 ID 참조';
COMMENT ON COLUMN TBL_ROUTINE_CHECK_ITEM.ITEM_ID IS '템플릿 항목 ID';
COMMENT ON COLUMN TBL_ROUTINE_CHECK_ITEM.IS_CHECKED IS '체크 여부 (T/F)';
COMMENT ON COLUMN TBL_ROUTINE_CHECK_ITEM.CHECK_TIME IS '체크한 시각';
COMMENT ON COLUMN TBL_ROUTINE_CHECK_ITEM.REMARK IS '비고';
COMMENT ON COLUMN TBL_ROUTINE_CHECK_ITEM.CREATED_AT IS '생성 시각';
COMMENT ON COLUMN TBL_ROUTINE_CHECK_ITEM.CREATED_BY IS '생성자';
COMMENT ON COLUMN TBL_ROUTINE_CHECK_ITEM.UPDATED_AT IS '수정 시각';
COMMENT ON COLUMN TBL_ROUTINE_CHECK_ITEM.UPDATED_BY IS '수정자';


-- TBL_ROUTINE_TEMPLATE: 루틴 템플릿 (메인)
CREATE TABLE TBL_ROUTINE_TEMPLATE (
    ID VARCHAR2(10 CHAR) PRIMARY KEY,
    TITLE VARCHAR2(100 CHAR) NOT NULL,
    TYPE VARCHAR2(20 CHAR),
    IS_USABLE CHAR(1),
    REMARK VARCHAR2(400 CHAR),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR2(36 CHAR),
    UPDATED_AT TIMESTAMP,
    UPDATED_BY VARCHAR2(36 CHAR)
);

COMMENT ON TABLE TBL_ROUTINE_TEMPLATE IS '루틴 템플릿 (메인)';
COMMENT ON COLUMN TBL_ROUTINE_TEMPLATE.ID IS '템플릿 ID (PK)';
COMMENT ON COLUMN TBL_ROUTINE_TEMPLATE.TITLE IS '템플릿 제목';
COMMENT ON COLUMN TBL_ROUTINE_TEMPLATE.TYPE IS '템플릿 종류';
COMMENT ON COLUMN TBL_ROUTINE_TEMPLATE.IS_USABLE IS '사용 가능 여부 (T/F)';
COMMENT ON COLUMN TBL_ROUTINE_TEMPLATE.REMARK IS '비고';
COMMENT ON COLUMN TBL_ROUTINE_TEMPLATE.CREATED_AT IS '생성 시각';
COMMENT ON COLUMN TBL_ROUTINE_TEMPLATE.CREATED_BY IS '생성자';
COMMENT ON COLUMN TBL_ROUTINE_TEMPLATE.UPDATED_AT IS '수정 시각';
COMMENT ON COLUMN TBL_ROUTINE_TEMPLATE.UPDATED_BY IS '수정자';


-- TBL_ROUTINE_TEMPLATE_ITEM: 루틴 템플릿 상세 항목
CREATE TABLE TBL_ROUTINE_TEMPLATE_ITEM (
    ID VARCHAR2(20 CHAR) PRIMARY KEY,
    TEMPLATE_ID VARCHAR2(10 CHAR) NOT NULL,
    TITLE VARCHAR2(100 CHAR) NOT NULL,
    ORDER_NO NUMBER,
    IS_USABLE CHAR(1),
    REMARK VARCHAR2(400 CHAR),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR2(36 CHAR),
    UPDATED_AT TIMESTAMP,
    UPDATED_BY VARCHAR2(36 CHAR)
);

COMMENT ON TABLE TBL_ROUTINE_TEMPLATE_ITEM IS '루틴 템플릿 (상세항목)';
COMMENT ON COLUMN TBL_ROUTINE_TEMPLATE_ITEM.ID IS '템플릿 항목 ID (PK)';
COMMENT ON COLUMN TBL_ROUTINE_TEMPLATE_ITEM.TEMPLATE_ID IS '템플릿 ID 참조';
COMMENT ON COLUMN TBL_ROUTINE_TEMPLATE_ITEM.TITLE IS '항목명';
COMMENT ON COLUMN TBL_ROUTINE_TEMPLATE_ITEM.ORDER_NO IS '순서';
COMMENT ON COLUMN TBL_ROUTINE_TEMPLATE_ITEM.IS_USABLE IS '사용 가능 여부 (T/F)';
COMMENT ON COLUMN TBL_ROUTINE_TEMPLATE_ITEM.REMARK IS '비고';
COMMENT ON COLUMN TBL_ROUTINE_TEMPLATE_ITEM.CREATED_AT IS '생성 시각';
COMMENT ON COLUMN TBL_ROUTINE_TEMPLATE_ITEM.CREATED_BY IS '생성자';
COMMENT ON COLUMN TBL_ROUTINE_TEMPLATE_ITEM.UPDATED_AT IS '수정 시각';
COMMENT ON COLUMN TBL_ROUTINE_TEMPLATE_ITEM.UPDATED_BY IS '수정자';